### ISSUE TITLE
Don't zoom in when GPS location is found

### ISSUE THREAD

**Issue by iandees** [bsudekum/MapTab#1]
I have random map + GPS location turned on and it just so happens that right when I open a new tab and start typing into the address bar, the GPS location is found and the map zooms in to my location. I have a top of the line retina Macbook Pro 13" and the poor thing can't handle the map zoom + fetching new tiles + autocompleting the URL. :smile: 

When in GPS mode, could it only pan to the new location? Maybe better would be to only pan if the GPS location is > X pixels away from the previous location so it won't do any movement if I haven't moved?

**Comment by bsudekum** [comment]
looking into this

**Comment by bsudekum** [comment]
@iandees can you test [`0.8`](https://chrome.google.com/webstore/detail/maptab/dmabflbokojjfjicmbjjfnmodihciemo)? In `0.7`, the map location was stored as boundaries. Now it's a simple lat, lng, zoom. Also the `map.locate()` maxzoom level is equal to the cached zoom level, so theoretically there should be no zooming. 

Let me know how it feels.

**Comment by iandees** [comment]
Sorry, I didn't have a way to test it easily.
