### ISSUE TITLE
Please show the bookmarks bar

### ISSUE THREAD

**Issue by jingsam** [bsudekum/MapTab#6]
Please show the bookmarks bar just like the default tab do, because it is the most use case. When you open a new tab, you click a bookmark and go to the website.

**Comment by mjgiarlo** [comment]
:+1: This would be most helpful, since that's where the link is to Chrome apps.

Any chance of this being added?

**Comment by bsudekum** [comment]
fixed!

**Comment by mjgiarlo** [comment]
:clap: Thanks!

**Comment by jingsam** [comment]
I checked the new version 1.12. I think the author misunderstands my meaning. What I prefer is show the bookmarks bar on the MapTab, not a link to default tab view

**Comment by mjgiarlo** [comment]
FWIW, the current solution works for me. I just needed an easy way to get to Chrome apps, which is now provided.

**Comment by jingsam** [comment]
@mjgiarlo , yes, this is a solution but not the best one. if you want to get Chrome apps, you need create a new tab and then click the apps link. You click twice to reach apps, while you could reach them in one click.
