### ISSUE TITLE
Can't edit Mapbox ID

### ISSUE THREAD

**Issue by bengolder** [bsudekum/MapTab#8]
I'm using the version in the Chrome Web Store:

> Version: 1.11
> Updated: May 12, 2015

It seems the Mapbox ID field is not editable.

![maptab](https://cloud.githubusercontent.com/assets/451510/7617347/5bde37cc-f95f-11e4-81ea-661cd3e1e1f5.gif)

**Comment by bsudekum** [comment]
Shoot, you're right. Will work on a fix tonight.

**Comment by bsudekum** [comment]
Fixed!

**Comment by bengolder** [comment]
:+1: awesome, thanks!
